spring:
  application:
    name: user_service
  profiles:
    active: dev # Change this to: dev, qa, or prod
  config:
    import: optional:configserver:http://localhost:8888


# Add this section to expose the refresh button:
management:
  endpoints:
    web:
      exposure:
        include: refresh, health


server:
  port: 8082

