server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user_service_route
              uri: http://localhost:8081 # DEV URL