spring:
  application:
    name: globalConfig
  profiles:
    active: native # Tells Config Server to read from local filesystem, NOT Git
  cloud:
    config:
      server:
        native:
          # Comma-separated list of all your service config folders
          search-locations: classpath:/user_service_config, classpath:/apiGateway_service_config

server:
  port: 8888 # Default port for Spring Cloud Config Server

