server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_user_dev
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update

environment:
  name: DEVELOPMENT

management:
  tracing:
    sampling:
      probability: 1.0 # 100% trace sampling (lower to 0.1 in prod)
  otlp:
    tracing:
      endpoint: http://localhost:4317/v1/traces # Sends data to OTel Collector
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics