server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_user_dev
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update

environment:
  name: DEVELOPMENT